### ISSUE TITLE
Infos bei Erstbenutztung sind durchsichtig

### ISSUE THREAD

**Issue by w3stley** [gandulf/DsaTab#289]
Hallo,
Ich habe mir gerade mal die App heruntergeladen und habe meine Helden importiert.
Dabei hat Dropbox sie zwar aufs Handy runtergeladen aber DsaTab hat sie nicht angezeigt.
Ich habe sie dann per Hand in den Stammordner eingefügt.

Was ich aber eigentlich anmerken wollte, ist das die Infos bei der Erstbenutzung transparent sind und ich sie daher nicht/kaum lesen kann.
![screenshot_2015-07-13-19-37-28 1](https://cloud.githubusercontent.com/assets/2928736/8656367/704cbb9e-2997-11e5-8fb6-91809b0675f5.png)

Ich habe mich auch mal fürs betatesting angemeldet. Wenn du willst würde ich dir gerne helfen.
Ich studiere Elektrotechnik und spiele seit ein paar Jahren DSA4.1 und benutze solange auch schon die Heldensoftware. Seit neustem habe ich auch ein Smartphone und da ich auf der FH und in der Schule Java gelernt habe, würde ich auch gerne was auf Android programmieren.\

MFG,
westley

**Comment by gandulf** [comment]
In der neuesten Version wurde Showcase view durch eine art AppIntro ersetzt, die den ganzen schirm ausfüllt, keine transparenz mehr.
