### ISSUE TITLE
DSATab crashes on ASUS MeMO Pad FHD 10 (ME302C)

### ISSUE THREAD

**Issue by Ibralosh** [gandulf/DsaTab#300]
I use DSATab for a while now, but with the last update it is crashing everytime I try to open my character on my tablet. The last version was working fine with this character.

**Comment by gandulf** [comment]
Hi, 
sorry for the inconviniec, but new version usually means new bugs ;-)
What android Version is running on your MeMo Pad?

**Comment by Ibralosh** [comment]
I'm running android 4.3 (latest version for this Tablet).

Regards,
Patrick

**Comment by Ibralosh** [comment]
I gave it another try now. It looks as if DSATab is crashing as soon as I open 'Ausrüstung' or 'Notizen'. My generated special view is not available at all.

**Comment by gandulf** [comment]
hmm 4.3 should be working fine, can you sent the xml file of your hero to gandulf.k@gmail.com so i can see if it's something special regarding your hero (special item, note ....)

**Comment by Ibralosh** [comment]
Well, there was an update in Google Play right now, so I gave that a try. I can reach 'Ausrüstung' and 'Notizen' now. Good job on that one. But DSATab still crashes as soon as I enter the Settings (Einstellungen). I don't think that these crashes are caused by my character sheet, but if you still need the xml file I will send it to you.

**Comment by Ibralosh** [comment]
It's working now, but issue #301 is also valid for this device.
